name: Generate 3D Contribution Graph

on:
  schedule:
    - cron: '0 0 * * *' # roda todo dia à meia-noite
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate 3D Contribution Graph
        uses: yoshi389111/github-profile-3d-contrib@main
        env:
          USERNAME: Buddhinha
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
